name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip libffi-dev libssl-dev \
            libncurses6 libncurses-dev \
            zlib1g-dev libsqlite3-dev \
            git python3 python3-pip python3-setuptools \
            build-essential openjdk-17-jdk wget

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true
          packages: build-tools;34.0.0 platforms;android-30 platform-tools

      - name: Manually install Apache ANT
        run: |
          mkdir -p ~/.buildozer/android/platform/
          wget -q https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
          tar -xzf apache-ant-1.9.4-bin.tar.gz -C ~/.buildozer/android/platform/

      - name: Link Android SDK to Buildozer path
        run: |
          mkdir -p ~/.buildozer/android/platform/
          ln -sfn /usr/local/lib/android/sdk ~/.buildozer/android/platform/android-sdk

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Clean old build artifacts
        run: |
          rm -rf .buildozer bin

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sprite-viewer.apk
          path: bin/*.apk
