name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK + licenses
        uses: android-actions/setup-android@v3
        with:
          api-levels: '30'                   # SDK platform
          build-tools: '34.0.0'              # Build-tools version
          cmdline-tools: 'latest'            # To make sdkmanager available
          accept-android-sdk-licenses: true

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sprite-viewer.apk
          path: bin/*.apk
