name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip libffi-dev libssl-dev \
            libncurses5 libncurses5-dev \
            zlib1g-dev libsqlite3-dev \
            git python3 python3-pip python3-setuptools \
            build-essential openjdk-17-jdk

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK manually
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg  # avoid SDK manager warnings

          yes | sdkmanager --licenses

          sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;34.0.0"

      - name: Clean build
        run: |
          rm -rf .buildozer bin

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sprite-viewer.apk
          path: bin/*.apk
