name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Buildozer dirs
        uses: actions/cache@v3
        with:
          path: ~/.buildozer ~/.buildozer_global
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libjpeg-dev libfreetype6-dev \
            libncurses5-dev libtool pkg-config zlib1g-dev \
            autoconf automake cython3
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo ln -sf "$(which cython3)" /usr/local/bin/cython

      - name: Install Android SDK + Inject licenses for build-tools 36
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools" "$HOME/android-sdk/licenses"
          curl -sSf https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools/"
          rm cmdline-tools.zip

          # Inject license hashes so sdkmanager won’t block on build-tools 36 license
          printf "8933bad161af4178b1185d1a37fbf41ea5269c55\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" \
            > "$HOME/android-sdk/licenses/android-sdk-license"

          # Install required packages
          yes | "$HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager" \
            --sdk_root="$HOME/android-sdk" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.0.0" \
            "ndk;23.1.7779620"

      - name: Accept remaining licenses
        run: yes | "$HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager" \
          --sdk_root="$HOME/android-sdk" --licenses

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.33

      - name: Build APK (verbose)
        env:
          ANDROIDSDK: $HOME/android-sdk
        run: buildozer --verbose android debug

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: |
            ./.buildozer/android/platform
