name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Buildozer directories
        uses: actions/cache@v3
        with:
          path: ~/.buildozer ~/.buildozer_global
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Install system dependencies (Ubuntu 24.04 fix + Cython)
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev \
            libjpeg-dev libfreetype6-dev libncurses5-dev libtool pkg-config \
            cmake zlib1g-dev autoconf automake cython

          # Fix for Ubuntu 24.04 missing libtinfo5
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

          # Workaround in case cython binary is missing
          sudo ln -sf "$(which cython3)" /usr/local/bin/cython || true

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -sSf https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/
          rm cmdline-tools.zip
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620"

      - name: Accept SDK licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer

      - name: Build APK (verbose)
        run: buildozer --verbose android debug

      - name: Upload Buildozer Logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: |
            ./.buildozer/android/platform
