name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git build-essential \
            libncurses5 openjdk-17-jdk \
            python3-pip python3-setuptools \
            libffi-dev libssl-dev \
            libsqlite3-dev libbz2-dev libreadline-dev zlib1g-dev \
            adb wget

          pip install --upgrade pip
          pip install buildozer cython==0.29.33 pillow kivy

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: spriteapp-debug-apk
          path: bin/*.apk
