name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libncurses6
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Set up Environment Variables
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROIDAPI=30" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Run Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SpriteViewer.apk
          path: bin/*.apk

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: .buildozer/android/platform/build-armeabi-v7a/build/outputs/logs/*
