name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip libffi-dev libssl-dev \
            libncurses6 libncurses-dev \
            zlib1g-dev libsqlite3-dev \
            git python3 python3-pip python3-setuptools \
            build-essential openjdk-17-jdk

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true
          packages: 
            - build-tools;34.0.0
            - platforms;android-30
            - platform-tools

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Clean build directories
        run: |
          rm -rf .buildozer bin

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sprite-viewer.apk
          path: bin/*.apk
